spring:
  profiles:
    active: prod

  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

  batch:
    jdbc:
      initialize-schema: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: {Google 계정 입력}
    password: {Google 계정에서 발급받은 앱 비밀번호 입력}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret_key: {secretKey 입력}
  access-validity-in-milliseconds: 600000
  refresh-validity-in-milliseconds: 1209600000

---

spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/board_jpa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234!

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        default_batch_fetch_size: 100

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        default_batch_fetch_size: 100
